contact/urls.py
from . import views
from django.urls import path, re_path
from django.conf.urls import url, include


app_name = 'contact'
urlpatterns = [

    #url(r'^$', views.message, name='contact'),
    path('', views.message, name='contact'),
    #url(r'^message/(?P<pk>\d+)/$', views.contact_message, name='contact_message'),
    path('message/<int:pk>/', views.contact_message, name='contact_message'),
    
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, re_path
from .views import home_view
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
#from django.contrib.sitemaps.views import sitemap

urlpatterns = [

	path('', home_view, name='home_view'),
	path('myuser/', include('myuser.urls')),
    path('contact/', include('contact.urls')),
    path('admin/', admin.site.urls),
    
]


## Production Settings
if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load staticfiles %}

{% load tz %}
{% get_current_timezone as TIME_ZONE %}


<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	{% block title %}
	<title>MyUser</title>
	{% endblock %}
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
	<script src="https://use.fontawesome.com/8aee6067b0.js"></script>

	{% block css %}
	<style>		
	</style>
	{% endblock %}
</head>

<body>
	<!-- messages -->
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
              <li{% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
	<!-- end messages -->
	

	{% block content %}
	{% endblock %}



	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
</body>

templates/contact_message.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Message</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
	<script src="https://use.fontawesome.com/8aee6067b0.js"></script>
	<style>
		h2:first-child {margin:80px 0;}
	</style>
</head>

<body>
	<div class="container">
		<div class="row">
			<div class="col-12">
				<h2><a href="{% url 'home_view' %}">Home</a></h2>
			</div>
		</div>

		<div class="row">
			<div class="col-12">
				<h1>Message from {{ message.name }}:</h1>
				<hr>
				<h3>Name: {{ message.name }}</h3>
				<h4>Email: {{ message.email }}</h4>
				<p>{{ message.message }}</p>
			</div>
		</div>
	</div>
</body>

templates/email_text.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

{% trans "Please go to the following page and choose a new password:" %}

    {% block reset_link %}
       {{ protocol }}{{ domain }}{% url 'confirm' uuid64=uuid64 token=token %}
       
    {% endblock %}
{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}

{% trans "Thanks for using our site!" %}



{% endautoescape %}

templates/home.html
{% extends "base.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}

{% block title %}
	<title>Home-MyUser</title>
{% endblock %}

{% block css %}
<style>
    body{position: relative;}
    footer{position: fixed;bottom:0; left:0;width: 100%;}
    form{width: 50%;}
    footer p{color:white;}
    footer .h3{color:white;}
  </style>
{% endblock %}


{% block content %}

  <div class="container">
    <div class="row">
      <div class="col-12">
          <h1 class="bg-secondary text-white text-center">Do I Work?</h1>
      </div>
    </div><!--./row-->

    <div class="row">
    	<div class="col-4">		
    		<img src="{{ request.user.avatar.url }}" class="rounded-circle img-fluid" width="100px">
    	</div>
    </div><!--./row-->
  </div><!--./container-->

  <!-- MAIN FOOTER -->
    <footer id="main-footer" class="bg-dark">
      <div class="container">
        <div class="row">
          <div class="col text-center">
            <div class="py-4">
              <h1 class="h3">Web-Worx</h1>
              <p>Copyright &copy; 2017</p>
              <button class="btn btn-primary" data-toggle="modal" data-target="#contactModal">Contact Us</button>
            </div>
          </div>
        </div>
      </div>
    </footer>

  <!-- Modal -->
  <div class="modal fade text-dark" id="contactModal">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title font-weight-bold mx-auto" id="contactModalTitle">
              Contact Us
            </h5>
          </div>
          <div class="modal-body d-flex justify-content-center">
            <form action="{% url 'contact:contact' %}" method="POST">
              {% csrf_token %}
              <div class="form-group">
                <label for="name">Name</label>
                {{ contact_form.name }}
              </div>
              <div class="form-group">
                <label for="email">Email</label>
                {{ contact_form.email }}
              </div>
              <div class="form-group">
                  <label for="message">Message</label>
                  {{ contact_form.message }}
              </div>
                <button class="btn btn-primary btn-block" type="submit">Submit</button>
            </form><!--end form-->
          </div><!--end modal-body-->
          <div class="modal-footer font-italic mx-auto">
              Copyright Web-Worx &copy;2017
          </div>
        </div>
      </div>
    </div>

  {% endblock %}

templates/register.html
{% extends "base.html" %}
{% load crispy_forms_tags %}



{% block title %}
	<title>Register MyUser</title>
{% endblock %}


{% block content %}

  <div class="container">
    <div class="row">
      <div class="col-12">
        <form action = "{% url 'register' %}" method="POST">
            {% csrf_token %}
         	{{ form|crispy }}
            <input class='btn btn-success' type='submit' value='Register'></input>
		</form>
      </div>
    </div><!--./row-->
  </div><!--./container-->

  {% endblock %}